# Default values for device-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: device-service
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 8080


postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: postgres
